- projects/tools.md
Added more to the tools page about linking 1password to Dropbox
> Added 1password link to Dropbox

- README.md
Editing whitespace for consistency so I can sleep at night.
> Superficial change to README.md for Github how-to

- staffing/onboarding/readme.md
This includes a couple links to blog posts that highlight the importance of an onboarding process.
> Add Further Reading section to Onboarding readme.md.

- staffing/job-descriptions/publici-news-developer-2014.md
This is almost, but not quite what we ran for the last news developer position we hired late last year.
> CPI job description

- staffing/onboarding/largo-umbrella-setup.md
- staffing/onboarding/readme.md
> Add largo-umbrella setup to Onboarding section.

- staffing/onboarding/os-x-setup.md
Adds wget and phpunit install info and link to wp unit testing post from INN Nerds blog.
> add wget and phpunit to cli tools in osx setup

- staffing/onboarding/largo-umbrella-setup.md
Note about virtualenvwrapper setup and alternative info about setup with a dummy SQL.
> updates to largo-umbrella setup

- staffing/job-descriptions/pro-publica-design-fellowship-2015.md
- staffing/job-descriptions/readme.md
- staffing/job-descriptions/sunlight-foundation-open-data-project-lead-2015.md
Job descriptions for Sunlight Foundation and ProPublica
-no word yet from Sunlight foundation to OK our posting
> add two job postings and update readme

- how-to-work-with-us/pull-requests-guide.md
Document explaining when to create a pull request, what information to include, and answers to some FAQs.  This guide is both for contributors outside INN and for new team members to learn about PRs.
Addresses issue #64 
What else should we include here?
> Created PR guide

- projects/book-club/facilitator-responsibilities.md
- projects/book-club/readme.md
- Replaces "leader" with "facilitator" in Book Club docs
- Removes references to polls in favor of facilitator choice of books
- Adds news@inn.org notification to list of facilitator responsibilities
> Book club changes

- projects/book-club/facilitator-responsibilities.md
> Book club changes 1

- staffing/onboarding/largo-umbrella-setup.md
https://codex.wordpress.org/htaccess
> add htaccess rewrite rules to instructions

- checklists/newsletter.md
> improving newsletter checklist

- staffing/onboarding/git-apps.md
* GitHub Desktop
* SourceTree
* GitBox
> add good GUIs for git

- how-we-work/meetings.md
Since we're talking about project process on this page, a link to the full Our Process page might come in handy.
> add useful link to Our Process page

- staffing/onboarding/accounts.md
Added links to some INN accounts/resources that were missing, and normalized punctuation (periods at the end of some lines were missing).
> Jack doc changes

- style-guides/code/php.md
> Switch from Zend to WordPress standards

- contributing.md
This adds a reminder to check for broken links to `contributing.md`.
> Reminder to check file paths when moving files

- checklists/child-themes.md
Now with a list of common problem areas in styles.
> More specific list of things to check in child themes.

- checklists/child-themes.md
This is because of [AJ-2](http://jira.inn.org/browse/AJ-2).
For example code, it links to Aspen, which contains a fix and a partial.
> Reminder about custom partials and LMP

- staffing/onboarding/os-x-setup.md
Explaining asset minification. Feel free to have a different and more explanatory link
> Included a link that explains minify

- communications/internal-communications/readme.md
- projects/office-hours/readme.md
Updates a bunch of links and some wording surrounding office hours.
https://nerds.inn.org/2016/07/13/changes-to-office-hours-moving-to-zoom-us/
> Switch office hours to Zoom.us

- staffing/onboarding/accounts.md
> Added information for setting up Google Analytics access for new users

- README.md
- Moved Ryan & Sinduja to Nerds Emeriti
- Added Gabriel & RC to current team list
> updating INN tech team staff list

- how-to-work-with-us/consulting/consulting-faq.md
- how-to-work-with-us/consulting/consulting-rates.md
- manifesto.md
- update the mission statement
- add the pets channel
- book club is now every other month
- s/HipChat/Slack/
- add a bunch of punctuation
> Updates from 2017-07-20 review

- how-we-work/tools.md
We've added new tools to our workflow and discontinued the use of others. This update reflects those changes.
> Updates to tools we use

- communications/newsletter/inndy.md
- communications/newsletter/readme.md
I'm going to check with @kaeti, @aschweigert and @rnagle to make sure that this is correct.
For #177.
> Initial commit of an oral history of Inndy in the newsletter.

- projects/largo/site-setup-valet.md
- Adds error message seen when importing a 219-megabyte database dump, with a working solution from StackOverflow.
Because I encountered this problem and wanted to fix it.
> Make note of a problem with importing large database dump, and solution

- checklists/readme.md
- how-we-work/dev-processes/install-ssl-flywheel.md
- how-we-work/dev-processes/install-ssl-wpengine.md
- how-we-work/dev-processes/install-ssl.md
- adds file for general SSL process
- adds file for Flywheel-specific SSL process
- moves existing WPE docs to new file specific to WPE
- starts list in `/checklists/readme.md` to index checklists that aren't in the checklists folder
because i'm working on this right now and noticed we had no docs for it.
> Add Flywheel SSL instructions and general SSL instructions

- staffing/offboarding/hellosign.md
- staffing/offboarding/readme.md
- staffing/offboarding/slack.md
Because of something Chip said.
Also, check your slack accounts.
> Add Hellosign/Docusign to offboarding docs

- checklists/hosted-site-turndown.md
- Creates a checklist for decommissioning sites as they move off our hosting
> A procedure for dealing with sites that move off our hosting

- staffing/miscellany/expense-reports.md
This pull request makes the following changes:
- Updates the expense report documentation so it lives someplace outside our inboxes.
Because we got a new form at the last staff meeting.
Features that this PR affects:
- `/staffing/miscellany/expense-reports.md`
Questions that need to be answered before merging:
Steps to test this PR:
1. Review https://github.com/INN/docs/blob/benlk-expense-reports-2020/staffing/miscellany/expense-reports.md
> Update expense report form documentation for 2020

- staffing/current-job-descriptions/developer.md
This file was last updated in 2017, so it's perhaps time to update it.
Requirements/preferences changes:
- Removes full LAMP stack and replaces it with a requirement for PHP/MySQL with a preference for Apache/Nginx. We don't really do server admin stuff.
- Changes server-side programming language experience from a preference to a bonus, because we haven't done any of that recently.
- Adds preference for local scripting languages, and explanation of how we use them.
- Replaces generic version control requirement with a Git requirement with GitHub preference.
- Adds React as a preferred frontend framework.
Wording changes:
- "Strong communication skills" was listed, but not as either a requirement or a preference. I've made it a requirement here, and rewritten the following sentences to …
> Update web dev position description
