INN/docs

- style-guides/code/wordpress.md
Addressing @aschweigert's suggestion (https://github.com/INN/Largo/issues/321#issuecomment-82467629) to document inline documentation standards for WordPress before beginning efforts to standardize our own inline documentation in Largo.
> Add WordPress Inline Docs Standards to WordPress style guide.

- manifesto.md
The link was relative so it generated a 404 on github instead of linking to nerds.inn.org.
> fix link to team blog

- checklists/releases.md
Updating `releases.md` with new steps based on [changes I've proposed for Largo](https://github.com/INN/Largo/pull/947).
> Updates to releases.md based on proposed changes to Largo's grunt workflow

- projects/largo/umbrella-setup.md
The link was 404. This fixes the link to the instructions for configuring sites in the network.
> Fixing link on member site setup instructions

- projects/wordpress-plugins/release.sh.md
- creates `release.sh.md` in `/projects/wordpress-plugins/` with instructions regarding the script, found in most of our maintained plugins.
Because we don't have any docs on usage or setup, and creating a separate GitHub repo for this one shell script seems strange.
> Add docs on release.sh to projects/wordpress-plugins

- projects/largo/database-reload.md
- Add WP-CLI command for database search-and-replace
- Document a `curl` command for fetching the database, assuming INN/secrets
WP-CLI because it's less effort than searchreplacedb2
curl because the `fab` command frequently fails. 😠
> Add WP-CLI option for database search-and-replace, curl command for fetching database

- projects/largo/database-reload.md
- `wp cli search-replace` is not a command but `wp search-replace` is; use the latter
- add command deactivating the redirection plugin on the main site, because it gets in the way of other commands
- add description of what's going on
- add reminder to update your `wp-cli`
The commands in #128 were incorrect in small details.
> Fix some wp-cli commands, improve descriptions of what's going on.

- checklists/releases.md
This PR includes the very essentials of prepping and releasing a plugin on the wordpress.org plugin directory.
> Essential checklist for deploying/releasing plugins to wordpress.org

- how-we-work/updating-plugins.md
Added a new document to how-we-work to cover the Largoproject Plugins Updating Process. This new doc has the filename `updating-plugins.md`.
We didn't previously have a process for updating plugins on the Largoproject multisite on WPEngine. This process needs to include testing for issues with the sites, since we've been burned by plugin update in the past. A thorough testing process should detect problems in time to either revert/restore, or allow us to fix the problems right away before any real harm is done.
Although it can be used now when updating largoproject plugins, this new document should be considered a draft. Details should be added about which plugins are potentially problematic, and as we use the process it should be updated to reflect when we learn.
> Add doc for Largoproject Plugins Updating Process

- events/code-of-conduct.md
- Add **Events** folder as container for all docs specifically pertinent to INN events
- Add newly-written doc **Code of Conduct for INN Conferences and Meetings** to the new Events folder
- We haven't had a place for documentation on INN events and need to begin providing for it in an organized way
- We have an upcoming workshop in Chicago
- We really should provide official policy for INN conferences and events in general
> Add Events folder for documentation related to INN events

- projects/largo/make-site-live.md
This is very specifically scoped for the "make it live" portion of any migration or new-site task.
> First draft of docs on taking a site from _.wpengine.com to _.com

- projects/largo/child-themes/new-site.md
- staffing/onboarding/accounts.md
- style-guides/code/readme.md
Companion pull request to number 2 in the secrets repository.
- Notes that secrets go in the secrets repo
- Fixes a link to the umbrella setup instructions
> notes on where secrets go and where the rules for secrets are

- projects/largo/database-reload.md
- use `--url=""` in all search-replace commands
- make note of `--network`
Because the command being run doesn't work without them.
> Update 'wp search-replace' commands to make them more effective.

- projects/largo/umbrella-setup.md
- Removes duplicate section about cloning Bitbucket, points to the Largo Umbrella's setup docs
- Replaces references to `vagrant snapshot take` with `vagrant snapshot save` to reflect recent versions of the snapshot plugin. https://www.vagrantup.com/docs/cli/snapshot.html
- Adds some common initial setup gotchas
> Replace Bitbucket with GitHub, update vagrant snapshot references

- communications/newsletter/editor-responsibilities.md
- communications/newsletter/sample-contributor-email.md
- projects/book-club/readme.md
- improves title/job description guidance for newsletter guests
- adds how to send contributions to us
- adds taxonomy term recommendations for newsletter posts on the Nerds blog
Because we're not consistent about tagging guest content as "guest".
Because sometimes it's easier to send someone a link to the newsletter contributor sample email, rather than sending them the email
> Add a little more guidance to the newsletter contributor email

- projects/largo/create-new-umbrella-repo.md
- imports umbrella repo setup docs at https://gist.github.com/benlk/e4f555eb817940b817354f598408e57c into INN's docs, resolving #106 
This needs review; it's mostly correct but there may be some gaps.
> move instructions for creating new umbrella repositories to INN/docs

- projects/wordpress-plugins/release.sh
- projects/wordpress-plugins/release.sh.md
- copies in `release.sh` from Ryan's github gist
- a temporary solution for https://github.com/INN/docs/issues/133
- because the canonical `release.sh` is not in any INN repo; just per-plugin derivative versions, and that issue has been open for more than a year with no resolution.
> Include release.sh in this repository

- staffing/miscellany/expense-reports.md
The Dropbox link is both nonfunctional and uninformative; this PR replaces the link with a description of where to find it in Dropbox and what its filename is.
> Correct expense report location

- README.md
- Move RC to Nerds Emeriti
- Add Tyler Machado
- Move Julia to the top of the list, 'cos she's director
> Update team staff list

- projects/wordpress-plugins/release.sh.md
- better setup instructions for first-time configuration of `release.sh`
- more-complete checklist for releasing plugins at later times
- common failure/error modes of `release.sh`
> Release.sh docs: additional info for later releases

- projects/dependencies/CMB2.md
- projects/dependencies/README.md
- projects/dependencies/pym.js.md
- projects/dependencies/release.sh.md
- adds a folder for keeping track of projects by their dependencies
- adds respective dependency files for CMB2, pym.js, and release.sh. release.sh is just a pointer to the list of plugins in release.sh.md elsewhere in this repository, though.
Basically: to make it easier to track down pym.js projects in the event of another security vulnerability disclosure like https://blog.apps.npr.org/2018/02/15/pym-security-vulnerability.html
> Create docs folder for keeping track of dependencies

- how-we-work/sunsetting-a-project.md
Adds a guideline document for writing project sunset docs.
Because we can't maintain everything forever, and so we need a set of guidelines on how to stop maintaining things.
This comes from the SRCCON 2017 [death of a project](https://etherpad.opennews.org/p/SRCCON2017-death-of-a-project) session. I'm proposing we include this in our docs because I think it should be part of our project planning process.
- What is missing in this?
- Where should sunsetting docs be included in each project?
- What needs to be added under "archive" and "shutdown"?
> Add project sunsetting questionnaire

- projects/wordpress-plugins/release.sh
- projects/wordpress-plugins/release.sh.md
This is in response to a question about excluding dependencies' .git
directories when those directories are included in composer-installed
packages.
> release.sh: explain blacklist glob to ignore dotfiles and dot-directories

- staffing/miscellany/expense-reports.md
- Describes location of Dropbox uploads of the forms introduced in May 2018
- Links to September 2018 revision of the employee handbook for expense report advice
- Marks the Hellosign instruction block as under review, because Chip said that the Hellosign requirement would be going away.
So that this doc is up to date
> Update expense report procedures for 2018 process

- staffing/onboarding/onboarding-checklist.md
If we're using the team weekly responsibilities list to track weekly responsibilities list, we should have new staff add themselves to that list.
> Onboarding: add addition of new staff to the team weekly responsibilities list

- staffing/onboarding/accounts.md
This pull request makes the following changes:
- Adds instructions for ReadTheDocs accounts
- Because I noticed I was the only current INN employee with access
Features that this PR affects:
- Onboarding, GitHub
Steps to test this PR:
1. Does the signup/onboarding flow make sense?
> Add ReadTheDocs to onboarding accounts list

- README.md
- how-to-work-with-us/readme.md
This pull request makes the following changes:
- Replaces old Chicago Tribune Apps blog links with archived version supplied by @aschweigert 
Resolves https://github.com/INN/docs/issues/225.
Steps to test this PR:
1. Click the link?
> Replace 404'd links to tribapps blog.

- projects/wordpress-plugins/release.sh.md
This pull request makes the following changes:
- adds instructions for using `release.sh` on a new device with a plugin repository that already exists
I'm always forgetting how to re-add the SVN repository, but if it's not there the release.sh file will throw errors.
Features that this PR affects:
- release.sh
INN Member/Labs Client requesting: MinnPost
> instructions for using a new device
